### ISSUE TITLE
getChildAdapterPosition: NoSuchMethodError

### ISSUE THREAD

**Issue by miguelmartin75** [timehop/sticky-headers-recyclerview#102]
When I've tried following along the readme and sample code, but when I run my application I run into this run-time exception: 

Note: I was initially running minimum API 14, but I tried 21, and still get the same error. Do you have any idea what the the cause for this could be?

```
java.lang.NoSuchMethodError: No virtual method getChildAdapterPosition(Landroid/view/View;)I in class Landroid/support/v7/widget/RecyclerView; or its super classes (declaration of 'android.support.v7.widget.RecyclerView' appears in /data/app/<app-name>/base.apk)
    at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.getItemOffsets(StickyRecyclerHeadersDecoration.java:59)
    at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:2744)
    at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:5543)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1332)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
    at android.view.View.layout(View.java:15596)
    at android.view.ViewGroup.layout(ViewGroup.java:4966)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2072)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1829)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
    at android.view.Choreographer.doCallbacks(Choreographer.java:580)
    at android.view.Choreographer.doFrame(Choreographer.java:550)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by jacobtabak** [comment]
What version of recyclerview library are you using?

**Comment by miguelmartin75** [comment]
7:21.0.3

**Comment by miguelmartin75** [comment]
So I assume your hunch was correct, it was due to the version of the recylcerview library I was using. I switch to the latest version (7:23.1.1) and it works :). Thanks
