### ISSUE TITLE
IndexOutBound

### ISSUE THREAD

**Issue by fjr619** [timehop/sticky-headers-recyclerview#21]
After your commit about "Draw headers with header ID = 0", the previous bug about delete last item is appear again. when i tried to delete my last item always get indexoutboundexception

**Comment by Flinbor** [comment]
Is it the same issue? when I try remove last item
java.lang.ArrayIndexOutOfBoundsException: length=118; index=-1

   @Override
    public long getHeaderId(int position) {
      if (position == 0) {
        return -1;
      } else {
        return getItem(position).charAt(0);
      }
    }

if I replace  "if (position == 0)"  to  "if (position == -1)" all works fine
in
library:0.3.6
sticky-headers-recyclerview/sample/src/main/java/com/timehop/stickyheadersrecyclerview/sample/MainActivity.java

**Comment by herriojr** [comment]
I'm getting a similar issue in 0.4.0.  What is triggering it for me is when I replace the dataset.  My startup for the headers looks like so:

```java
final StickyRecyclerHeadersDecoration d = new StickyRecyclerHeadersDecoration(mAdapter);
        mAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onChanged() {
                d.invalidateHeaders();
            }
        });
```

Then later when I do the replace where the top item in the list disappears (happens when I remove the top item twice), it crashes like so:

```
05-28 10:43:58.822  10509-10509/com.myapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.stubhub.music.android, PID: 10509
    java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.myapp.EventsAdapter.onBindHeaderViewHolder(EventsAdapter.java:269)
            at com.timehop.stickyheadersrecyclerview.caching.HeaderViewCache.getHeader(HeaderViewCache.java:35)
            at com.timehop.stickyheadersrecyclerview.HeaderPositionCalculator.itemIsObscuredByHeader(HeaderPositionCalculator.java:166)
            at com.timehop.stickyheadersrecyclerview.HeaderPositionCalculator.getFirstViewUnobscuredByHeader(HeaderPositionCalculator.java:145)
            at com.timehop.stickyheadersrecyclerview.HeaderPositionCalculator.isStickyHeaderBeingPushedOffscreen(HeaderPositionCalculator.java:91)
            at com.timehop.stickyheadersrecyclerview.HeaderPositionCalculator.getHeaderBounds(HeaderPositionCalculator.java:60)
            at com.timehop.stickyheadersrecyclerview.StickyRecyclerHeadersDecoration.onDrawOver(StickyRecyclerHeadersDecoration.java:96)
            at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:2739)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2178)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatch
```

**Comment by mleroy** [comment]
+1 @herriojr

**Comment by jacobtabak** [comment]
Happy to investigate and fix if you make a fork that reproduces the issue

**Comment by mleroy** [comment]
I was getting this exception when updating the data set (header ids 1, 2) to include a new section at the start, plus non-section (header id -1) items (-1, 0, -1, 1, 2). The exception no longer occurs since I made my second non-section item part of the section right above it (-1, 0, 0, 1, 2).

I wasn't able to reproduce the same crash in the sample project with a similar data set, so I am missing a piece of the puzzle unfortunately. I'll come back to this if I can find another way to reproduce the issue.
